### ISSUE TITLE
Add Title to STIX Indicators

### ISSUE THREAD

**Issue by anlklsim** [anl-cyberscience/FlexTransform#25]
I notice when viewing STIX docs in Soltra or with STIX->HTML conversion, the fact that we have no title elements in our indicators makes it very hard to view a summary form (I'd have to show you a snapshot of what it looks like).

Adding an Indicator:Title element to each indicator (can be the same text as in the Description element) will help greatly in these alternate viewer tools.

**Comment by mghenderson** [comment]
We support indicators have a title, but they only get added if the source file has titles (I've included examples below).  We can set default titles for indicators, but as that value will be used for all indicators w/o a defined title, we'd probably want to do that in a site-specific config.  Suggestions?

##### title in source
```xml
<stix:Indicator id="isa:guide.999191.Indicator-30f9b6e4-d3a7-52b0-a123-1dfc1b353ffb" timestamp="2016-06-10T23:33:04+00:00" xsi:type='indicator:IndicatorType' version="2.1.1">
	<indicator:Title>Original CRISP Report Document</indicator:Title>
	<indicator:Description>CRISP-16-669.pdf</indicator:Description>
	<indicator:Observable id="isa:guide.999191.Observable-ceb2bb7b-f09a-51b1-a847-dc8d0a4d57fb">
		<cybox:Object id="isa:guide.999191.Object-4e68c02d-1ca7-547d-a2cb-e352dcf573f2">
			<cybox:Properties xsi:type="ArtifactObj:ArtifactObjectType" suspected_malicious="false" type="File" content_type="application/pdf">
				<ArtifactObj:Packaging>
					<ArtifactObj:Encoding algorithm="Base64"/>
				</ArtifactObj:Packaging>
				<ArtifactObj:Raw_Artifact>[PDF]</ArtifactObj:Raw_Artifact>
			</cybox:Properties>
		</cybox:Object>
	</indicator:Observable>
</stix:Indicator>
```
##### w/o title in source
```xml
<stix:Indicator id="isa:guide.999191.Indicator-374d83a4-2b21-578c-b180-9efdaca0d187" timestamp="2016-06-10T23:33:04+00:00" xsi:type='indicator:IndicatorType' version="2.1.1">
	<indicator:Type xsi:type="stixVocabs:IndicatorTypeVocab-1.1">IP Watchlist</indicator:Type>
	<indicator:Description>CRISP Report Indicator</indicator:Description>
	<indicator:Observable id="isa:guide.999191.Observable-07fc13e1-512e-52bf-97a5-2767678d55ef">
		<cybox:Object id="isa:guide.999191.Object-3511f778-5fc2-5c82-94f1-4f8a2a7517a6">
			<cybox:Properties xsi:type="AddressObj:AddressObjectType" category="ipv4-addr">
				<AddressObj:Address_Value condition="Equals">[IP ADDRESS]</AddressObj:Address_Value>
			</cybox:Properties>
		</cybox:Object>
	</indicator:Observable>
</stix:Indicator>	
```

**Comment by anlklsim** [comment]
One example from AIS has the report number as the title in each indicator, although, that's not much better for looking at in a summary (no title vs the same title over and over).  I don't think there is the equivalent of a title in the cfm1.3 alert data.

**Comment by mghenderson** [comment]
So at this point, we're probably talking about adding a transform function (called during output if there isn't a value already present) to determine what we're going to have in the title block, as it's going to have to look several places for the title if we're trying to infer it in an automated fashion.  Not a problem, but we'll probably want to decide the order we start looking for things.

**Comment by mghenderson** [comment]
So, per Dan's recommendation, I'm going to add `FlexT Converted Alert File` as the default value for the STIX title, unless you disagree.
