### ISSUE TITLE
Config File - CSV fields empty space

### ISSUE THREAD

**Issue by mghenderson** [anl-cyberscience/FlexTransform#40]
FlexT doesn't support spaces around field values in the config file.  Add support for stripping leading/trailing white space for the field values in the config file. 

**Config - Current**
valid = `Fields = indicator,indicatorType,reason,detectedTime`
invalid = `Fields = indicator, indicatorType,reason,detectedTime`
invalid = `Fields = indicator,indicatorType ,reason,detectedTime`

**Config - Future**
valid = `Fields = indicator,indicatorType,reason,detectedTime`
valid = `Fields = indicator, indicatorType,reason,detectedTime`
valid = `Fields = indicator,indicatorType ,reason,detectedTime`

**Comment by smsullivan** [comment]
Was actually investigating this with LQMT, specifically for FlexText. Seems like a problem with TOML.

Would a possible fix for this be to make Field definitions arrays? Whitespace is automatically ignored in this case, so no stripping is required on our end. 
EX: 
```
Fields = ["indicator", "indicatorType", "reason", "detectedTime"]
```

It might even give some more flexibility in formatting in the actual config file. More information here: https://github.com/toml-lang/toml#array
