### ISSUE TITLE
Sample files available:

### ISSUE THREAD

**Issue by ChrisStrasburg** [anl-cyberscience/FlexTransform#7]
Probably one of the first things users want to do is try out the install to make sure it works. One way to allow them to do this is to provide sample files, and then include in the user readme.md file instructions on how to run FlexT on those sample files.

We should make samples available publicly and include the command to run them in the readme.md file.

**Comment by pbenzoni** [comment]
I can put together (more) sample files, where would you like me to put them?

**Comment by mghenderson** [comment]
Done in earlier commit (4fe747363ef274477492732daaac442dc2620446)
